# Generated by Django 2.1.7 on 2019-07-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date_time', models.DateTimeField()),
                ('exit_date_time', models.DateTimeField()),
                ('Location', models.CharField(max_length=40)),
                ('truck_count', models.IntegerField()),
                ('plateno', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
