# Generated by Django 2.1.7 on 2019-08-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date_time', models.DateTimeField()),
                ('exit_date_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='truck',
            name='entry_date_time',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='exit_date_time',
        ),
        migrations.AlterField(
            model_name='truck',
            name='plateno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='recordtime',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.Truck'),
        ),
    ]
