# Generated by Django 2.1.7 on 2019-07-18 06:25

from django.db import migrations, models
import django.db.models.deletion
import sacks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SackLoading',
            fields=[
                ('sack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sacks.Sack')),
                ('loading_date_time', models.DateTimeField()),
                ('sack_img', models.ImageField(upload_to=sacks.models.loadingimagepath)),
            ],
            bases=('sacks.sack',),
        ),
        migrations.CreateModel(
            name='SackUnloading',
            fields=[
                ('sack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sacks.Sack')),
                ('unloading_date_time', models.DateTimeField()),
                ('sack_img', models.ImageField(upload_to=sacks.models.unloadingimagepath)),
            ],
            bases=('sacks.sack',),
        ),
        migrations.AddField(
            model_name='sack',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.Truck'),
        ),
    ]
