# Generated by Django 2.1.7 on 2019-07-18 06:25

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to=companies.models.imagepath),
        ),
    ]
